import Head from 'next/head';
import Image from 'next/image';
import Nav from '../components/Nav';
import '../i18n';
import Bg from '../assets/images/bg.jpg';
import { useTranslation } from 'react-i18next';
import { MdArrowForwardIos } from 'react-icons/md';
export default function Home() {
  const { t } = useTranslation();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Nav />
      <div className='bg md:h-[807px] lg:h-[773.094px] absolute inset-0  border-b-8 border-[#55799d]'>
        <Image src={Bg.src} alt='' fill />
        <div className='img-gradient z-10'></div>
      </div>
      <div className='relative z-20 mx-auto max-w-[950px] text-center py-[100px] px-[5%]'>
        <h1 className='text-5xl text-white font-bold mx-32'>{t('slogan')}</h1>
        <h2 className='py-4 px-10 text-3xl text-white'>{t('subtitle')}</h2>
        <form>
          <h3 className='text-xl text-white mx-16 pb-10'>
            {t('titleAddMail')}
          </h3>
          <div className='flex'>
            <input
              type='text'
              placeholder='Email address'
              className='pl-5 grow'
            />
            <button className='red-button rounded-r flex text-3xl items-center'>
              Get Started <MdArrowForwardIos style={{ margin: 0 }} />
            </button>
          </div>
        </form>
      </div>
    </>
  );
}
